---

version: '2'

services:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      SCARLETT_HOST: 0.0.0.0
      SCARLETT_PORT: 8080
      SCARLETT_DEBUG: 1
      SCARLETT_DEFAULT_IMG: https://placeimg.com/640/480/nature/sepia
