---

version: '2'

services:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      SCARLETT_HOST: 0.0.0.0
      SCARLETT_PORT: 8000
      SCARLETT_DEBUG: 1
      SCARLETT_DEFAULT_IMG: https://docs.prismapp.io/assets/images/prism-logo.png
